spring.application.name=stats-service
spring.datasource.url=jdbc:postgresql://${STATS_DB_HOST:stats-db}:${STATS_DB_PORT:5432}/${STATS_DB_NAME:statsdb}
spring.datasource.username=${STATS_DB_USER:statsuser}
spring.datasource.password=${STATS_DB_PASSWORD:statspass}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
