spring.application.name=workout-service
spring.datasource.url=jdbc:postgresql://${WORKOUT_DB_HOST:workout-db}:${WORKOUT_DB_PORT:5432}/${WORKOUT_DB_NAME:workoutdb}
spring.datasource.username=${WORKOUT_DB_USER:workoutuser}
spring.datasource.password=${WORKOUT_DB_PASSWORD:workoutpass}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

exercise.api.base-url=https://oss.exercisedb.dev/api/v1

jwt.secret=${JWT_SECRET}